Pkg.Desc=System Image arm64-v8a with Google API.
Pkg.Revision=1
Pkg.Dependencies=emulator#31.1.1
AndroidVersion.ApiLevel=26
SystemImage.Abi=arm64-v8a
SystemImage.TagId=google_apis
SystemImage.TagDisplay=Google APIs
SystemImage.GpuSupport=true
Addon.VendorId=google
Addon.VendorDisplay=Google Inc.

